### ISSUE TITLE
Merge with concurrent-ruby gem

### ISSUE THREAD

**Issue by headius** [headius/thread_safe#46]
The concurrent-ruby gem (https://github.com/jdantonio/concurrent-ruby) is rapidly becoming the "java.util.concurrent of Ruby". There's a ton of folks contributing, it supports damn near every concurrency construct there is, and work is ongoing to build native VM support for the major implementations. I believe it's the library we should all collaborate on.

To that end, I'd like to merge this gem into that one. We'd do another release of this gem with a dependency on concurrent-ruby, and the contents of this gem would merge into that codebase. We're probably going to put everything under the new ruby-concurrency org (https://github.com/ruby-concurrency).

Hopefully no contributors have objections. I think most folks doing threading in Ruby will appreciate having a single library dependency that provides a full set of concurrency features.

cc @jdantonio @chrisseaton @pitr-ch @thedarkone

**Comment by colinsurprenant** [comment]
Ah! Just found this issue after [asking the question](https://groups.google.com/d/msg/concurrent-ruby/ASgXSnsCmnM/yFiaJGxMrj8J) in the concurrent-ruby group. Anything preventing moving on with this merge? Need help?

**Comment by jdantonio** [comment]
@colinsurprenant We chose to focus our efforts on merging the `ruby-atomic` gem first, which required us to give significant thought to how best to handle the compiled extensions within `concurrent-ruby`. Our efforts in 0.7.x didn't work out as well as we had hoped (see [issue 186](https://github.com/ruby-concurrency/concurrent-ruby/issues/186)). This lead us down the current 0.8.x path ([issue 221](https://github.com/ruby-concurrency/concurrent-ruby/issues/221) and [PR 205](https://github.com/ruby-concurrency/concurrent-ruby/pull/205)). This also lead us to [taking over the maintenance of the ref gem](https://github.com/ruby-concurrency/ref/issues/13). All of that took much lunger than expected...

Once we get 0.0.8 released (scheduled for later this month) we should be in a good position to merge `thread_safe` into `concurrent-ruby`. We'd love to have your help at that time!

**Comment by pitr-ch** [comment]
@colinsurprenant Thanks for the offer to help! If you have any questions about concurrent-ruby, you can find me and others on https://gitter.im/ruby-concurrency/concurrent-ruby

**Comment by colinsurprenant** [comment]
Thanks @jdantonio for filling me in on the background info for this. will digest that and followup post 0.8. @pitr-ch Perfect! I will.

**Comment by jdantonio** [comment]
I've opened a new discussion of this merge in the concurrent-ruby repo [here](https://github.com/ruby-concurrency/concurrent-ruby/issues/230).

Can we please close this thread and move the discussion there?
