### ISSUE TITLE
push v0.3.5 tag to GitHub

### ISSUE THREAD

**Issue by ktdreyer** [headius/thread_safe#48]
When you tag releases, would you mind pushing the tags to GitHub? For example the latest version on Rubygems.org is 0.3.5, but the v0.3.5 tag is missing from the repository.

**Comment by donv** [comment]
Hi @ktdreyer !

I think you will find it here:  

https://github.com/ruby-concurrency/thread_safe/releases

The gem has moved to

https://github.com/ruby-concurrency/thread_safe

The link from RubyGems.org to the gem Home Page was updated with the 0.3.5 release.

**Comment by ktdreyer** [comment]
Thanks for the pointer! I will send future PRs and issues there.
